//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotepadShop.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationEn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NotepadShop.Localization.Resources.LocalizationEn", typeof(LocalizationEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new item.
        /// </summary>
        internal static string addNewItemMessage {
            get {
                return ResourceManager.GetString("addNewItemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email should contains symbol @.
        /// </summary>
        internal static string incorrectEmailValidation {
            get {
                return ResourceManager.GetString("incorrectEmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect login or password.
        /// </summary>
        internal static string incorrectLoginOrPassword {
            get {
                return ResourceManager.GetString("incorrectLoginOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should contains at least 8 haracters, 1 uppercase character, 1 lowercase character and 1 digit.
        /// </summary>
        internal static string incorrectParrwordValidation {
            get {
                return ResourceManager.GetString("incorrectParrwordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string itemName {
            get {
                return ResourceManager.GetString("itemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string loginLabel {
            get {
                return ResourceManager.GetString("loginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in or register.
        /// </summary>
        internal static string loginOrRegisterLabel {
            get {
                return ResourceManager.GetString("loginOrRegisterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string logOutLabel {
            get {
                return ResourceManager.GetString("logOutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notepads.
        /// </summary>
        internal static string notepadsCategory {
            get {
                return ResourceManager.GetString("notepadsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string passwordLabel {
            get {
                return ResourceManager.GetString("passwordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pens.
        /// </summary>
        internal static string pensCategory {
            get {
                return ResourceManager.GetString("pensCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string registerLabel {
            get {
                return ResourceManager.GetString("registerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mistake while registration.
        /// </summary>
        internal static string registrationIdentityError {
            get {
                return ResourceManager.GetString("registrationIdentityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with such email  is already registered.
        /// </summary>
        internal static string userWithSuchEmailAlreadyExists {
            get {
                return ResourceManager.GetString("userWithSuchEmailAlreadyExists", resourceCulture);
            }
        }
    }
}
